app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from .views import login, Index, RegisterStudent

from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/login/')),
    path('index/', Index.as_view(), name="index"),
    path('administrador/', include('panel_admin.urls', namespace='panel_admin')),
    path('profesor/', include('panel_teacher.urls', namespace='panel_teacher')),
    path('estudiante/', include('panel_student.urls', namespace='panel_student')),
    path('admin/', admin.site.urls),
	path('login/', login, name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),

    path('registro/', include([
        path('estudiante/', RegisterStudent.as_view(), name="register-student"),
        ])),
]

app/panel_admin/modules/tutorias/urls.py
from django.urls import path, include

from .views import (Index, IndexIndividual, CreateIndividual, ApprovedIndividual, DetailIndividual, RejectIndividual,
    IndexRegularizacion, CreateRegularizacion, ApprovedRegularizacion, DetailRegularizacion, RejectRegularizacion,
    IndexAcademica, CreateAcademica, ApprovedAcademica, DetailAcademica, RejectAcademica,
    IndexPares, CreatePares, ApprovedPares, DetailPares, RejectPares)

app_name = "tutorias"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('individual/', include([
        path('', IndexIndividual.as_view(), name="index-individual"),
        path('<pk>/', DetailIndividual.as_view(), name="detail-individual"),
        path('nueva/', CreateIndividual.as_view(), name="create-individual"),
        path('aprobar/<pk>', ApprovedIndividual.as_view(), name="approved-individual"),
        path('rechazar/<pk>', RejectIndividual.as_view(), name="reject-individual")
    ])),
    path('regularizacion/', include([
        path('', IndexRegularizacion.as_view(), name="index-regularizacion"),
        path('<pk>/', DetailRegularizacion.as_view(), name="detail-regularizacion"),
        path('nueva/', CreateRegularizacion.as_view(), name="create-regularizacion"),
        path('aprobar/<pk>', ApprovedRegularizacion.as_view(), name="approved-regularizacion"),
        path('rechazar/<pk>', RejectRegularizacion.as_view(), name="reject-regularizacion")
    ])),
    path('academica/', include([
        path('', IndexAcademica.as_view(), name="index-academica"),
        path('<pk>/', DetailAcademica.as_view(), name="detail-academica"),
        path('nueva/', CreateAcademica.as_view(), name="create-academica"),
        path('aprobar/<pk>', ApprovedAcademica.as_view(), name="approved-academica"),
        path('rechazar/<pk>', RejectAcademica.as_view(), name="reject-academica")
    ])),
    path('pares/', include([
        path('', IndexPares.as_view(), name="index-pares"),
        path('<pk>/', DetailPares.as_view(), name="detail-pares"),
        path('nueva/', CreatePares.as_view(), name="create-pares"),
        path('aprobar/<pk>', ApprovedPares.as_view(), name="approved-pares"),
        path('rechazar/<pk>', RejectPares.as_view(), name="reject-pares")
    ])),
]

app/panel_student/modules/tutorias/urls.py
from django.urls import path, include

from .views import (Index, IndexIndividual, DetailIndividual, CreateIndividual, UpdateIndividual,
    IndexRegularizacion, DetailRegularizacion, CreateRegularizacion, UpdateRegularizacion,
    IndexAcademica, DetailAcademica, CreateAcademica, UpdateAcademica,
    IndexPares, DetailPares, CreatePares, UpdatePares,)

app_name = "tutorias"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('individual/', include([
        path('', IndexIndividual.as_view(), name="index-individual"),
        path('nueva/', CreateIndividual.as_view(), name="create-individual"),
        path('<pk>/', DetailIndividual.as_view(), name="detail-individual"),
        path('<pk>/editar/', UpdateIndividual.as_view(), name="update-individual")
    ])),
    path('regularizacion/', include([
        path('', IndexRegularizacion.as_view(), name="index-regularizacion"),
        path('nueva/', CreateRegularizacion.as_view(), name="create-regularizacion"),
        path('<pk>/', DetailRegularizacion.as_view(), name="detail-regularizacion"),
        path('<pk>/editar/', UpdateRegularizacion.as_view(), name="update-regularizacion")
    ])),
    path('academica/', include([
        path('', IndexAcademica.as_view(), name="index-academica"),
        path('nueva/', CreateAcademica.as_view(), name="create-academica"),
        path('<pk>/', DetailAcademica.as_view(), name="detail-academica"),
        path('<pk>/editar/', UpdateAcademica.as_view(), name="update-academica")
    ])),
    path('pares/', include([
        path('', IndexPares.as_view(), name="index-pares"),
        path('nueva/', CreatePares.as_view(), name="create-pares"),
        path('<pk>/', DetailPares.as_view(), name="detail-pares"),
        path('<pk>/editar/', UpdatePares.as_view(), name="update-pares")
    ])),
]

app/panel_teacher/urls.py
from django.urls import path, include, re_path

from .views import Index

app_name = 'panel_teacher'

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('tutorias/', include('panel_teacher.modules.tutorias.urls', namespace="tutorias")),
]

app/panel_teacher/models.py
from django.db import models

# Create your models here.

app/tutors/models.py
from django.db import models
from app.models import DateTimeStampModel, PersonModel
# Create your models here.
from app.catalogues import (TURNO_MATUTINO, TURNO_VESPERTINO, TURNO_CHOICE)

class StudentTutoriasIndividual(DateTimeStampModel):
    class Meta:
        verbose_name = "Tutoría Individual" # alumno El alumno escoge el profe
        verbose_name_plural = "Tutoría Individual"
        ordering = ['-create_timestamp']

    student = models.ForeignKey("students.Student", on_delete=models.CASCADE)
    teacher_tutor = models.ForeignKey('teachers.Teacher', verbose_name="Escoge al profesor", on_delete=models.CASCADE, null=True)
    is_assigned = models.NullBooleanField('¿Está asignado?', editable=False)
    start = models.DateField('Fecha de inicio de las tutorias', null=True, blank=True)
    end = models.DateField('fecha de fin de las tutorias', null=True, blank=True)
    location = models.CharField('Localización', max_length=256, null=True, blank=True)
    reason = models.TextField('Motivos', max_length=512, null=True)
    reason_reject = models.TextField('Motivos de rechazo', max_length=512, null=True, blank=True)
    is_finished = models.NullBooleanField('¿Está asignado?', default=False)

class StudentTutoriasRegularizacion(DateTimeStampModel):
    class Meta:
        verbose_name = "Tutoría de regularización"
        verbose_name_plural = "Tutorías de regularización" # se inscibe y escoge la materia especifica
        ordering = ['-create_timestamp']

    student = models.ForeignKey("students.Student", on_delete=models.CASCADE)
    materia = models.ForeignKey('Materia', on_delete=models.CASCADE)
    teacher_tutor = models.ForeignKey('teachers.Teacher', verbose_name="Profesor Tutor", on_delete=models.CASCADE, null=True)
    is_assigned = models.NullBooleanField('¿Está asignado?')
    start = models.DateField('Fecha de inicio de las tutorias', null=True, blank=True)
    end = models.DateField('fecha de fin de las tutorias', null=True, blank=True)
    location = models.CharField('Localización', max_length=256, null=True, blank=True)
    reason = models.TextField('Motivos', max_length=512, null=True)
    reason_reject = models.TextField('Motivos de rechazo', max_length=512, null=True)
    is_finished = models.NullBooleanField('¿Está asignado?', default=False)

class StudentTutoriasAcademica(DateTimeStampModel):
    class Meta:
        verbose_name = "Tutoría por recuperación academica"
        verbose_name_plural = "Tutoríaa por recuperación academica"
        ordering = ['-create_timestamp']
        # Cuando alguien tiene dictamen o esta por desfase (elige su materia, mireya (el administrador) elige quien se lo coje)

    student = models.ForeignKey("students.Student", on_delete=models.CASCADE)
    materia = models.ForeignKey('Materia', on_delete=models.CASCADE)
    teacher_tutor = models.ForeignKey('teachers.Teacher', on_delete=models.CASCADE, null=True)
    is_assigned = models.NullBooleanField('¿Está asignado?')
    start = models.DateField('Fecha de inicio de las tutorias', null=True, blank=True)
    end = models.DateField('fecha de fin de las tutorias', null=True, blank=True)
    location = models.CharField('Localización', max_length=256, null=True, blank=True)
    reason = models.TextField('Motivos', max_length=512, null=True)
    reason_reject = models.TextField('Motivos de rechazo', max_length=512, null=True, blank=True)
    is_finished = models.NullBooleanField('¿Está asignado?', default=False)

class StudentTutoriasPares(DateTimeStampModel):
    class Meta:
        verbose_name = "Tutoría entre pares"
        verbose_name_plural = "Tutorías entre pares"
        ordering = ['-create_timestamp']
        # Es tutoria entre alumnos, se escoge materia, el administrador asigna al alumno tutor (Es 1 a 1) (El maestro tutado dice en que materias puede apoyar)

    student = models.ForeignKey("students.Student", on_delete=models.CASCADE)
    materia = models.ForeignKey('Materia', on_delete=models.CASCADE)
    student_tutor = models.ForeignKey('students.Student', verbose_name="Alumno tutor", on_delete=models.CASCADE, null=True, related_name="student_tutor")
    is_assigned = models.NullBooleanField('¿Está asignado?')
    start = models.DateField('Fecha de inicio de las tutorias', null=True, blank=True)
    end = models.DateField('fecha de fin de las tutorias', null=True, blank=True)
    location = models.CharField('Localización', max_length=256, null=True, blank=True)
    reason = models.TextField('Motivos', max_length=512, null=True)
    reason_reject = models.TextField('Motivos de rechazo', max_length=512, null=True, blank=True)
    is_finished = models.NullBooleanField('¿Está asignado?', default=False)

    def save(self):
        if self.student_tutor:
            print(11)
            if self.is_finished == True:
                print(22)
                self.student_tutor.is_available = True
            else:
                print(333)
                self.student_tutor.is_available = False
            self.student_tutor.save()
        return super().save()

class GroupTutorias(DateTimeStampModel):
    class Meta:
        verbose_name = "Grupo de tutorias"
        verbose_name_plural = "Grupos de Tutorias"

    group = models.ForeignKey('Group', verbose_name="Grupo", on_delete=models.CASCADE, null=True)
    period_school = models.ForeignKey('PeriodSchool', verbose_name="Periodo Escolar", on_delete=models.CASCADE, null=True)
    teacher = models.ForeignKey('teachers.Teacher', on_delete=models.CASCADE, null=True)

    start = models.DateField("Inicio de la tutoria Grupal", blank=True, null=True)
    end = models.DateField("Fin de la tutorias grupal", blank=True, null=True)


    def __str__(self):
        return "{}".format(self.group)

    @property
    def is_available(self):
        if self.students.all().count() >= 15:
            return False
        return True

class Group(DateTimeStampModel):
    class Meta:
        verbose_name="Grupos"
        verbose_name_plural = "Grupos"

    name = models.CharField('Nombre', max_length=64)
    turno = models.CharField(max_length=8, choices=TURNO_CHOICE, default=TURNO_MATUTINO)

    def __str__(self):
        return "{}".format(self.name)


class PeriodSchool(DateTimeStampModel):
    class Meta:
        verbose_name = "Periodo Escolar"
        verbose_name_plural = "Periodos Escolares"

    name = models.CharField("Periodo Escolar", max_length=32)

    def __str__(self):
        return "{}".format(self.name)

class Note(models.Model):
    class Meta:
        verbose_name = "Nota"
        verbose_name_plural = "Notas"
        ordering = ["-pk"]

    group_tutorias = models.ForeignKey('GroupTutorias', on_delete=models.CASCADE, null=True, blank=True)
    tutorias_individual = models.ForeignKey('StudentTutoriasIndividual', on_delete=models.CASCADE, null=True, blank=True)
    tutorias_regularizacion = models.ForeignKey('StudentTutoriasRegularizacion', on_delete=models.CASCADE, null=True, blank=True)
    tutorias_academica = models.ForeignKey('StudentTutoriasAcademica', on_delete=models.CASCADE, null=True, blank=True)
    tutorias_pares = models.ForeignKey('StudentTutoriasPares', on_delete=models.CASCADE, null=True, blank=True)

    content = models.TextField('Nota', max_length=256)

    def __str__(self):
        return self.content


class TypeTutorias(models.Model):
    class Meta:
        verbose_name = "Tipos de tutorias"
        verbose_name_plural = "Tipos de tutorias"

    name = models.CharField('Nombre', max_length=64)
    description = models.CharField('descripción', max_length=64)

    def __str__(self):
        return "{}".format(self.name)


class Materia(models.Model):
    class Meta:
        verbose_name = "Materia"
        verbose_name_plural = "Materias"

    name = models.CharField("Nombre", max_length=64)

    def __str__(self):
        return "{}".format(self.name)


class Tema(models.Model):
    class Meta:
        verbose_name = "Tema"
        verbose_name_plural = "Temas"

    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    name = models.CharField('nombre', max_length=512)

    def __str__(self):
        return "{} > {}".format(self.materia, self.name)

app/panel_teacher/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class Index(TemplateView):
    template_name = "panel_teacher/index.html"

app/panel_teacher/templates/panel_teacher/tutorias/academica/detail.html
{% extends 'panel_teacher/base.html' %}

{% block title_page %}
  <h1>Detalle de Tutoria Academica en Riesgo</h1>
{% endblock %}

{% block main_content %}

<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        Informacion General
      </div>
      <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Profesor tutor: <span class="text-muted">{{ object.teacher_tutor }}</span></li>
        <li class="list-group-item">Materia: <span class="text-muted">{{ object.materia }}</span></li>
        <li class="list-group-item">Alumno tutado: <span class="text-muted">{{ object.student }}</span></li>
        <li class="list-group-item">Inicio: <span class="text-muted">{{ object.start }}</span></li>
        <li class="list-group-item">Hasta: <span class="text-muted">{{ object.end }}</span></li>
        <li class="list-group-item">Locación: <span class="text-muted">{{ object.location }}</span></li>

      </ul>
      </div>
      <div class="card-footer">
        {% if not object.is_finished %}
        <a class="btn btn-danger btn-sm" href="{% url 'panel_teacher:tutorias:finish-academica' object.pk %}">Finalizar</a>
        <a class="btn btn-warning btn-sm" href="{% url 'panel_teacher:tutorias:update-academica' object.pk %}">Editar</a>
        {% else %}
        <div class="alert alert-dark" role="alert">
          Esta tutoria ya ha finalizado
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">

        Informacion General
        <div class="float-right">
          {% if not object.is_finished %}
          <a class="btn btn-primary btn-sm" href="{% url 'panel_teacher:tutorias:note-academica' object.pk %}"><i class="fas fa-plus"></i></a>
          {% endif %}
        </div>
      </div>
      <div class="card-body">
      <ul class="list-group list-group-flush">
        {% for note in object.note_set.all %}
          <li class="list-group-item">{{ note.content }}</li>
        {% empty %}
          <li class="list-group-item">Sin Notas</li>
        {% endfor %}
      </ul>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/panel_teacher/templates/panel_teacher/tutorias/academica/finish.html
{% extends 'panel_admin/base.html' %}


{% block title_page %}
<h1>Se dará por finalizado la tutoria</h1>
<p>Esta accion es irreversible, ¡Gracias!</p>
{% endblock %}


{% block main_content %}
<div class="form-group">
  <div class="col-md-12">
    {% include 'panel_admin/form.html' %}
  </div>
</div>

{% endblock %}

app/panel_teacher/templates/panel_teacher/tutorias/academica/index.html
{% extends 'panel_teacher/base_list.html' %}

{% block title_page %}
  <h1> Mis tutorias academicas en situación de riesgo </h1>
{% endblock %}

{% block main_content %}

  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Estudiante</th>
          <th scope="col">Materia</th>
          <th scope="col">Profesor Tutor</th>
          <th scope="col">Inicio</th>
          <th scope="col">Fin</th>
          <th scope="col">Localización</th>
          <th scope="col">¿En curso?</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object_list %}
        <tr>
          <td><a href="{% url 'panel_teacher:tutorias:detail-academica' item.pk %}">{{ item.student }}</a></td>
          <td>{{ item.materia }}</td>
          <td>{{ item.teacher_tutor|default_if_none:"N/A" }}</td>
          <td>{{ item.start|default_if_none:"N/A" }}</td>
          <td>{{ item.end|default_if_none:"N/A" }}</td>
          <td>{{ item.location|default_if_none:"N/A" }}</td>
          <td>
            {% if item.is_finished %}
              <span class="badge badge-secondary">Ha finalizado</span>
            {% else %}
              <span class="badge badge-danger">En Progreso</span>
            {% endif %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td>No hay Solicitud de Tutorias</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

app/panel_teacher/templates/panel_teacher/tutorias/academica/note.html
{% extends 'panel_admin/base.html' %}


{% block title_page %}
<h1>Agregar Nota</h1>
{% endblock %}


{% block main_content %}
<div class="form-group">
  <div class="col-md-12">
    {% include 'panel_admin/form.html' %}
  </div>
</div>

{% endblock %}

app/panel_teacher/templates/panel_teacher/tutorias/academica/update.html
{% extends 'panel_admin/base.html' %}


{% block title_page %}
<h1>Actualizar datos de la tutoria</h1>
<p>El alumno tutado es: {{ object.student }}</p>
{% endblock %}


{% block main_content %}
<div class="form-group">
  <div class="col-md-12">
    {% include 'panel_admin/form.html' %}
  </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
  $( "#id_start" ).datepicker({
    dateFormat: "dd/mm/yy"
  });
  $( "#id_end" ).datepicker({
    dateFormat: "dd/mm/yy"
  });
</script>
{% endblock %}