app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from .views import login, Index, RegisterStudent

from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/login/')),
    path('index/', Index.as_view(), name="index"),
    path('administrador/', include('panel_admin.urls', namespace='panel_admin')),
    path('profesor/', include('panel_teacher.urls', namespace='panel_teacher')),
    path('estudiante/', include('panel_student.urls', namespace='panel_student')),
    path('admin/', admin.site.urls),
	path('login/', login, name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),

    path('registro/', include([
        path('estudiante/', RegisterStudent.as_view(), name="register-student"),
        ])),
]

app/panel_student/modules/profile/urls.py
from django.urls import path, include

from .views import (Detail, Update)

app_name = "profile"

urlpatterns = [
    path('<pk>/', Detail.as_view(), name='detail'),
    path('<pk>/editar', Update.as_view(), name='update'),
]

app/panel_student/modules/tutorias/urls.py
from django.urls import path, include

from .views import (Index, IndexIndividual, DetailIndividual, CreateIndividual, UpdateIndividual,
    IndexRegularizacion, DetailRegularizacion, CreateRegularizacion, UpdateRegularizacion,
    IndexAcademica, DetailAcademica, CreateAcademica, UpdateAcademica,
    IndexPares, DetailPares, CreatePares, UpdatePares,)

app_name = "tutorias"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('individual/', include([
        path('', IndexIndividual.as_view(), name="index-individual"),
        path('nueva/', CreateIndividual.as_view(), name="create-individual"),
        path('<pk>/', DetailIndividual.as_view(), name="detail-individual"),
        path('<pk>/editar/', UpdateIndividual.as_view(), name="update-individual")
    ])),
    path('regularizacion/', include([
        path('', IndexRegularizacion.as_view(), name="index-regularizacion"),
        path('nueva/', CreateRegularizacion.as_view(), name="create-regularizacion"),
        path('<pk>/', DetailRegularizacion.as_view(), name="detail-regularizacion"),
        path('<pk>/editar/', UpdateRegularizacion.as_view(), name="update-regularizacion")
    ])),
    path('academica/', include([
        path('', IndexAcademica.as_view(), name="index-academica"),
        path('nueva/', CreateAcademica.as_view(), name="create-academica"),
        path('<pk>/', DetailAcademica.as_view(), name="detail-academica"),
        path('<pk>/editar/', UpdateAcademica.as_view(), name="update-academica")
    ])),
    path('pares/', include([
        path('', IndexPares.as_view(), name="index-pares"),
        path('nueva/', CreatePares.as_view(), name="create-pares"),
        path('<pk>/', DetailPares.as_view(), name="detail-pares"),
        path('<pk>/editar/', UpdatePares.as_view(), name="update-pares")
    ])),
]

app/panel_student/urls.py
from django.urls import path, include, re_path

from .views import Index

app_name = 'panel_student'

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('tutorias/', include('panel_student.modules.tutorias.urls', namespace="tutorias")),
    path('mi-perfil/', include('panel_student.modules.profile.urls', namespace="profile"))

]

app/panel_student/models.py
from django.db import models

# Create your models here.

app/panel_student/modules/profile/views.py
from datetime import datetime
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from students.models import Student

from django.views.generic import (
    TemplateView, RedirectView, FormView,
    CreateView, DetailView, UpdateView, DeleteView, ListView
)

from tutors.models import StudentTutoriasPares

class BaseView(LoginRequiredMixin):
    template_dir = "panel_student/profile/"
    model = Student

    def get_student(self):
        return self.request.user.user_student if self.request.user.user_student else None

class Detail(BaseView, DetailView):
    template_name = BaseView.template_dir + "detail.html"

class Update(BaseView, UpdateView):
    template_name = BaseView.template_dir + "update.html"
    fields = ['name', 'last_name', 'boleta', 'turno', 'is_tutor', 'materias']

    def get_success_url(self):
        return reverse('panel_student:profile:detail', kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        if form.instance.is_tutor and not StudentTutoriasPares.objects.filter(is_finished=False, student_tutor=self.object):
            form.instance.is_available = True

        return super().form_valid(form)

app/panel_student/modules/tutorias/views.py
from datetime import datetime
from django import forms
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from operator import itemgetter

from tutors.models import (StudentTutoriasIndividual, StudentTutoriasRegularizacion,
    StudentTutoriasAcademica, StudentTutoriasPares)

from django.views.generic import (
    TemplateView, RedirectView, FormView,
    CreateView, DetailView, UpdateView, DeleteView, ListView
)


class BaseView(LoginRequiredMixin):
    template_dir = "panel_student/tutorias/"

    def get_student(self):
        return self.request.user.user_student if self.request.user.user_student else None

class Index(BaseView, TemplateView):
    template_name = BaseView.template_dir + 'index.html'


class IndexIndividual(BaseView, ListView):
    model = StudentTutoriasIndividual
    template_name = BaseView.template_dir + 'individual/index.html'

    def get_queryset(self):
        student = BaseView.get_student(self)
        return StudentTutoriasIndividual.objects.filter(student=student)

class DetailIndividual(BaseView, DetailView):
    model = StudentTutoriasIndividual
    template_name = BaseView.template_dir + 'individual/detail.html'

class CreateIndividual(BaseView, CreateView):
    model = StudentTutoriasIndividual
    template_name = BaseView.template_dir + 'individual/create.html'
    fields = ['teacher_tutor', 'reason']

    def form_valid(self, form):
        student = BaseView.get_student(self)
        form.instance.student = student
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-individual')

class UpdateIndividual(BaseView, UpdateView):
    model = StudentTutoriasIndividual
    template_name = BaseView.template_dir + 'individual/update.html'
    fields = ['teacher_tutor', 'reason']

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-individual')


class IndexRegularizacion(BaseView, ListView):
    model = StudentTutoriasRegularizacion
    template_name = BaseView.template_dir + 'regularizacion/index.html'

    def get_queryset(self):
        student = BaseView.get_student(self)
        return StudentTutoriasRegularizacion.objects.filter(student=student)

class DetailRegularizacion(BaseView, DetailView):
    model = StudentTutoriasRegularizacion
    template_name = BaseView.template_dir + 'regularizacion/detail.html'

class CreateRegularizacion(BaseView, CreateView):
    model = StudentTutoriasRegularizacion
    template_name = BaseView.template_dir + 'regularizacion/create.html'
    fields = ['materia', 'reason']

    def form_valid(self, form):
        student = BaseView.get_student(self)
        form.instance.student = student
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-regularizacion')

class UpdateRegularizacion(BaseView, UpdateView):
    model = StudentTutoriasRegularizacion
    template_name = BaseView.template_dir + 'regularizacion/update.html'
    fields = ['materia', 'reason']

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-regularizacion')


class IndexAcademica(BaseView, ListView):
    model = StudentTutoriasAcademica
    template_name = BaseView.template_dir + 'academica/index.html'

    def get_queryset(self):
        student = BaseView.get_student(self)
        return StudentTutoriasAcademica.objects.filter(student=student)

class DetailAcademica(BaseView, DetailView):
    model = StudentTutoriasAcademica
    template_name = BaseView.template_dir + 'academica/detail.html'

class CreateAcademica(BaseView, CreateView):
    model = StudentTutoriasAcademica
    template_name = BaseView.template_dir + 'academica/create.html'
    fields = ['materia', 'reason']

    def form_valid(self, form):
        student = BaseView.get_student(self)
        form.instance.student = student
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-academica')

class UpdateAcademica(BaseView, UpdateView):
    model = StudentTutoriasAcademica
    template_name = BaseView.template_dir + 'academica/update.html'
    fields = ['materia', 'reason']

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-academica')


class IndexPares(BaseView, ListView):
    model = StudentTutoriasPares
    template_name = BaseView.template_dir + 'pares/index.html'

    def get_queryset(self):
        student = BaseView.get_student(self)
        return StudentTutoriasPares.objects.filter(student=student)

class DetailPares(BaseView, DetailView):
    model = StudentTutoriasPares
    template_name = BaseView.template_dir + 'pares/detail.html'

class CreatePares(BaseView, CreateView):
    model = StudentTutoriasPares
    template_name = BaseView.template_dir + 'pares/create.html'
    fields = ['materia', 'reason']

    def form_valid(self, form):
        student = BaseView.get_student(self)
        form.instance.student = student
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-pares')

class UpdatePares(BaseView, UpdateView):
    model = StudentTutoriasPares
    template_name = BaseView.template_dir + 'pares/update.html'
    fields = ['materia', 'reason']

    def get_success_url(self):
        return reverse('panel_student:tutorias:index-pares')

app/panel_student/views.py
from django.views.generic import TemplateView

# Create your views here.

class Index(TemplateView):
    template_name = "panel_student/index.html"

app/panel_student/templates/panel_student/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Tutorias ESIME-IPN{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'assets/css/panel_custom.css' %}">

    {% block css %}
    {% endblock %}
  </head>
  <body>

  {% include 'panel_student/navbar.html' %}

  <div class="container">
    {% block title_page %}
    {% endblock %}

    {% block main_content %}
    {% endblock %}
  </div>
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
  <!-- jquery-U -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <!-- bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock %}
  </body>
</html>

app/panel_student/templates/panel_student/base_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Tutorias ESIME-IPN{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'assets/css/panel_custom.css' %}">

    {% block css %}
    {% endblock %}
  </head>
  <body>

  {% include 'panel_student/navbar.html' %}

  <div class="container">
    {% block title_page %}
    {% endblock %}

    {% block main_content %}
    {% endblock %}
  </div>
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
  <!-- jquery-U -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <!-- bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock %}
  </body>
</html>

app/panel_student/templates/panel_student/form-delete.html
{% load i18n widget_tweaks %}
<div class="container">
  <div class="col-md-12">
    <form id="form" METHOD="post" ACTION="" enctype="multipart/form-data">
        {% csrf_token %}
        <strong class="text-center">Este cambio es irreversible ¿Desea continuar?</strong>
        <div class="text-center mt-4">
          <a onclick="window.history.back()" href="javascript:void(0)" class="btn btn-dark btn-back text-white">No, cancelar</a>
          <button type="submit" class="btn btn-danger">Si, continuar</button>
        </div>
    </form>
  </div>
</div>

app/panel_student/templates/panel_student/form.html
{% load i18n static widget_tweaks %}
<div class="container">
  <div class="col-md-12">
    <form id="form" METHOD="post" ACTION="" enctype="multipart/form-data">
        <div class="row mx-1">
            <div class="col-md-12">
             {% csrf_token %}

              {% for field in form %}
              <div class="row mt-4">
                  <label class="lead">
                      <span for="{{ field.id }}">{{ field.label }}
                              {% if field.field.required %}
                                  <span>*</span>
                              {% endif %}
                      </span>
                  </label>
                  {{ field|add_class:"form-control" }}
                  {% if field.help_text %}
                      <div class="alert alert-light" role="alert">{{ field.help_text }}</div>
                  {% endif %}

                  {% if field.errors %}
                      <span class="text text-danger">{{ field.errors }}</span>
                  {% endif %}
              </div>
              {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group text-center mt-4">
            <a onclick="window.history.back()" class="btn btn-danger mr-2 btn-back text-white"><i class="fas fa-times-circle fa-fw"></i> Cancelar</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-check-circle fa-fw"></i> Guardar</button>
        </div>
    </form>
  </div>
</div>

app/panel_student/templates/panel_student/index.html
{% extends 'panel_student/base.html' %}


{% block title_page %}
<h1>Bienvenido {{ request.user.user_student }}</h1>
<h5>Aqui pódras ver el estado de tus tutorias, realizar solitudes y encontrar material de apoyo</h5>
{% endblock %}


{% block main_content %}
<div class="text-center">
  <div class="row form-group justify-content-md-center pt-5 mt-5">
     <div class="card-deck">

         <div class="card col-md-6">
           <div class="card-body">
             <h4 class="card-title"><strong>Tutorias</strong></h4>
             <a href="{% url 'panel_student:tutorias:index' %}"><i class="text-tut fa-7x fas fa-users"></i></a>
             <p class="card-text pt-3">Módulo para ver y solictar tutorias</p>
           </div>
         </div>

         <div class="card col-md-6">
           <div class="card-body">
             <h4 class="card-title"><strong>Mi Perfil</strong></h4>
             <a href="{% url 'panel_student:profile:detail' request.user.user_student.pk %}"><i class="text-tut fa-7x fas fa-user"></i></a>
             <p class="card-text pt-3">Módulo para poder ver mi perfil</p>
           </div>
         </div>

     </div>
   </div>
</div>

{% endblock %}

app/panel_student/templates/panel_student/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">TUTORIAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        {% url 'panel_student:index' as url %}
        {% if url == request.path %}
        <a class="nav-link active-tut" href="{{ url }}"><strong>Home</strong><span class="sr-only">(current)</span></a>
        {% else %}
        <a class="nav-link" href="{{ url }}">Home</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% url 'panel_student:tutorias:index' as url %}
        {% if url == request.path %}
        <a class="nav-link active-tut" href="{{ url }}"><strong>Tutorias</strong><span class="sr-only">(current)</span></a>
        {% else %}
        <a class="nav-link" href="{{ url }}">Tutorias</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% url 'panel_student:profile:detail' request.user.user_student.pk as url %}
        {% if url == request.path %}
        <a class="nav-link active-tut" href="{{ url }}"><strong>Mi perfil</strong><span class="sr-only">(current)</span></a>
        {% else %}
        <a class="nav-link" href="{{ url }}">Mi Perfil</a>
        {% endif %}
      </li>

    </ul>
      <a href="{% url 'logout' %}" class="btn btn-outline-danger my-2 my-sm-0" type="submit">Cerrar Sesión</a>
  </div>
</nav>